### ISSUE TITLE
[1.10.2] Vanilla Chiseled Leaves Don't Render Properly

### ISSUE THREAD

**Issue by oitsjustjose** [ChiselsAndBits/Chisels-and-Bits#202]
Using:
* MinecraftForge 12.18.3.2185
* Chisels and Bits 12.8
* MCMultiPart 1.3.0 (also tested on 2.0.0_88 with same results)

In an isolated test environment with only these two mods installed, the leaf rendering is very weird. I can't narrow it down specifically, so let me explain my debugging process and see if it helps. On my singleplayer world ([modlist here](http://goo.gl/DV8p1T)), I noticed leaves were rendering [like this](http://puu.sh/sOILu/65fd5ffc51.png) and thought it odd. I then went and tested in a separate instance with only Forge 2185 and Chisels and Bits 12.8, and the results were somehow stranger still. 

**Before Changing MipMap Slider:**

![vanilla cb mipmap changed](https://cloud.githubusercontent.com/assets/3887324/21166305/a554cf06-c172-11e6-8253-510efa5222fe.png)

**After Changing MipMap Slider (but before restart):**

![vanilla cb mipmap changed](https://cloud.githubusercontent.com/assets/3887324/21166310/ae10fa66-c172-11e6-9c2a-7b452c5570dd.png)

After restarting the game, the leaves' transparency reverted to the non-transparent type from before the slider had been adjusted. Weirder still is that in this same test world, I decided to start adding mods one-by-one from my Singleplayer instance to see if I could replicate the weird _white_-filled leaves, but after adding literally the entire modpack, I could not get them to appear white again!

**Comment by AlgorithmX2** [comment]
I have a feeling this has to do with a bug I fixed, but forgot to release on 1.10.2, mind trying to reproduce with https://dl.dropboxusercontent.com/u/9117298/cb/anti-builds/chiselsandbits-12.9.jar ?

**Comment by oitsjustjose** [comment]
Here's what I've figured out in testing that build:

1. The weird white textures? Resource pack. I never use fast settings, so I didn't know the fast leaves used white.... that's hideous.

2. 12.9 did not fix the issue, what did however, is disabling the static renderer. Is this intended or something I should've done the whole time? It doesn't seem to be affecting my FPS at all, and I've got at least 200 Chiseled Bit blocks in my world.

![2016-12-13_20 46 09](https://cloud.githubusercontent.com/assets/3887324/21166709/344a4428-c175-11e6-8ec2-e681fa29d0a1.png)

**Comment by AlgorithmX2** [comment]
Hmm, Well the static renderer and the dynamic render should be capable of rendering leaves, the only real difference is which pipleine is used, C&B's or Vanillas ( which tends to stall ) but over all the dynamic renderer is "more expensive" since its more render calls per frame, not immediately slow, but it can slow things down.

Since that didn't fix it I'll have to do some research, its rather odd that it renders as opaque, then later changes to render as masked, but culls faces...

**Comment by AlgorithmX2** [comment]
After reviewing the "fix" I've found that my caching of layer data occurs before mine-craft has decided which mod to use for leaves.

Which explains the strange behavior, and its update with the mipmap slider.

**Comment by oitsjustjose** [comment]
Oh! That took a shockingly little amount of time to determine!

**Comment by AlgorithmX2** [comment]
Mostly because I already figured that that change was related, I just needed to confirm some things, the fix however remains to be seen I'll have to consider that.

**Comment by AlgorithmX2** [comment]
I believe I've fixed this on 1.11 I'll have to make a new build for 1.10 however.

**Comment by AlgorithmX2** [comment]
Released.
